<?php
$otw_wpl_grid_manager_object->labels['OTW Grid Manager Light']=esc_html__('OTW Grid Manager Light', 'widgetize-pages-light');
$otw_wpl_grid_manager_object->labels['Info']=esc_html__('Info', 'widgetize-pages-light');
$otw_wpl_grid_manager_object->labels['Add Row']=esc_html__('Add Row', 'widgetize-pages-light');
$otw_wpl_grid_manager_object->labels['Add some rows and columns in the rows.<br />Then you will be able to add items (actual content) in the columns.']=otw_esc_text('Add some rows and columns in the rows.<br />Then you will be able to add items (actual content) in the columns.', 'widgetize-pages-light');
$otw_wpl_grid_manager_object->labels['Choose column type']=esc_html__('Choose column type', 'widgetize-pages-light');
$otw_wpl_grid_manager_object->labels['Advanced settings']=esc_html__('Advanced settings', 'widgetize-pages-light');
$otw_wpl_grid_manager_object->labels['Mobile Grid']=esc_html__('Mobile Grid', 'widgetize-pages-light');
$otw_wpl_grid_manager_object->labels['The grid has two modes of adapting for small displays like phones.<br />The first requires no work at all - the grid will linearize on a small device so your columns stack vertically (all in one column). If you don’t know what you are doing leave it as is and it should be all fine.<br />The other mode can take your existing grid elements and attach them to a six column phone grid. This means you can have 1, 2 or 3 columns on mobile devices. Note that you need to have all columns in a given row set up correctly in order to make it work.<br />Here is an example of two columns in a row.<br />This is correct: 1/2 +1/2<br />This is incorrect: 2/3 + 1/2 because it is more than a full row<br />This is incorrect: 1/3 + 1/3 because it doesn’t make a full row.']=otw_esc_text('The grid has two modes of adapting for small displays like phones.<br />The first requires no work at all - the grid will linearize on a small device so your columns stack vertically (all in one column). If you don’t know what you are doing leave it as is and it should be all fine.<br />The other mode can take your existing grid elements and attach them to a six column phone grid. This means you can have 1, 2 or 3 columns on mobile devices. Note that you need to have all columns in a given row set up correctly in order to make it work.<br />Here is an example of two columns in a row.<br />This is correct: 1/2 +1/2<br />This is incorrect: 2/3 + 1/2 because it is more than a full row<br />This is incorrect: 1/3 + 1/3 because it doesn’t make a full row.', 'widgetize-pages-light');
$otw_wpl_grid_manager_object->labels['Save']=esc_html__('Save', 'widgetize-pages-light');
$otw_wpl_grid_manager_object->labels['Cancel']=esc_html__('Cancel', 'widgetize-pages-light');
?>